version: "3.1"

services:

  nginx:
    container_name: 'project-nginx'
    image: nginx:stable
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  api:
    container_name: 'project-api'
    build:
      context: /projenice/application/projenice-api/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /projenice/application/projenice-api/target/base-api.jar:/base-api.jar
    depends_on:
      - db

  db:
    container_name: 'data-base'
    image: mariadb:10
    restart: always
    volumes:
      - /projenice/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306