version: "3.1"

services:

   api:
     container_name: 'project-api'
     build:
       context: /projenice/application/projenice-api/
       dockerfile: Dockerfile
     restart: always
     depends_on:
       - db
     ports:
       - 80:8080

   db:
     container_name: 'data-base'
     image: mariadb:10
     restart: always
     volumes:
       - /projenice/data:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=root
     ports:
       - 3306:3306